type: kafka
inputs:
  - enrich_sensor
bootstrap_servers: "kafka-13776261-aware.l.aivencloud.com:19583"
topic: "{{ kafka_topic }}"
encoding:
  codec: json
  except_fields:
    - kafka_topic
tls:
  enabled: true
  ca_file: "/etc/vector/certs/ca_certificate"
  crt_file: "/etc/vector/certs/access_certificate"
  key_file: "/etc/vector/certs/access_key"

healthcheck:
  enabled: false

buffer:
  type: disk
  max_size: 268435488 # 256MB buffer if Kafka is temporarily unreachable