deployment:
  image:
    repository: ghcr.io/rodis/inference-car-door-opened
    tag: "sha-c61af3c"
    pullPolicy: IfNotPresent
  env:
    KAFKA_BOOTSTRAP_SERVERS:
      valueFrom:
        configMapKeyRef:
          name: inference-worker-config
          key: KAFKA_BOOTSTRAP_SERVERS
    VECTOR_BASE_URL:
      valueFrom:
        configMapKeyRef:
          name: inference-worker-config
          key: VECTOR_BASE_URL
    REDIS_HOST:
      valueFrom:
        secretKeyRef:
          name: redis-credentials
          key: REDIS_HOST
    REDIS_PORT:
      valueFrom:
        secretKeyRef:
          name: redis-credentials
          key: REDIS_PORT
    REDIS_DB:
      valueFrom:
        secretKeyRef:
          name: redis-credentials
          key: REDIS_DB
    REDIS_USERNAME:
      valueFrom:
        secretKeyRef:
          name: redis-credentials
          key: REDIS_USERNAME
    REDIS_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: redis-credentials
          key: REDIS_PASSWORD
  volumes:
    kafka-ssl:
      secret:
        secretName: kafka-ssl-credentials
        items:
          - key: ca-certificate
            path: ca-cert.pem
          - key: access-certificate
            path: access-cert.pem
          - key: access-key
            path: access-key.pem
  volumeMounts:
    kafka-ssl:
      mountPath: /etc/kafka/ssl
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
