resources:
  - ../../base
patches:
  - target:
      kind: Ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: vector.prod.rods.me
      - op: replace
        path: /spec/tls/0/hosts
        value: [vector.prod.rods.me]