apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: inference-redis-credentials
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: aiven-redis-configuration
  config: prd
  secrets:
    - REDIS_DB
    - REDIS_HOST
    - REDIS_PASSWORD
    - REDIS_PORT
    - REDIS_USERNAME
  managedSecret:
    name: redis-credentials
    namespace: inference
    type: Opaque
