from typing import Protocol


class Observer(Protocol):
    def on_start(self, topics: list[str]) -> None: ...
    def on_received(self, payload: dict) -> None: ...
    def on_inference(self, result: dict) -> None: ...
    def on_error(self, error: Exception, context: str | None = None) -> None: ...
    def on_shutdown(self) -> None: ...
