apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: kafka-aiven-credentials-for-vector
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: kafka-aiven-credentials
  config: prd
  nameTransformer: lower-snake
  secrets:
    - ACCESS_CERTIFICATE
    - ACCESS_KEY
    - CA_CERTIFICATE
  managedSecret:
    name: kafka-aiven-credentials-for-vector
    namespace: inference
    type: Opaque
