apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-home-arrival
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/rodis/inference.git
    targetRevision: main
    path: deploy/kustomize/base

  destination:
    server: https://kubernetes.default.svc
    namespace: inference

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
