apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: home-arrival
name: application
releaseName: home-arrival
version: 6.16.1
repo: https://stakater.github.io/stakater-charts
valuesFile: values.yml
namespace: inference
